# Generated by Django 2.2.12 on 2020-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField()),
                ('date_add', models.DateTimeField(null=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('sujet', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(null=True)),
                ('date_add', models.DateTimeField(null=True)),
                ('date_update', models.DateTimeField(null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
