# Generated by Django 2.2.12 on 2020-09-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20200921_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='nom',
        ),
        migrations.AddField(
            model_name='about',
            name='titre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='image/about'),
        ),
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
